# Java version to be used in GCP
runtime: java11

# The type of virtual machine GCP will use to run the application
# https://cloud.google.com/appengine/docs/standard#instance_classes
# https://cloud.google.com/appengine/quotas#Deployments
instance_class: F2

# Hardcoded to a single instance just to be extra sure nothing will suddenly make GAE spawn multiple instances and make
# the app leave free tier. Also, considering the intended audience, one instance is more than enough.
automatic_scaling:
  max_instances: 1